//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class retornoConsulta
{
    public retornoConsulta()
    {
        remessas = new List<retornoConsultaRemessa>();
    }

    private string statusField;

    private string mensagemField;

    private string totalField;

    private List<retornoConsultaRemessa> remessasField;

    /// <remarks/>
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    public string mensagem
    {
        get
        {
            return this.mensagemField;
        }
        set
        {
            this.mensagemField = value;
        }
    }

    /// <remarks/>
    public string total
    {
        get
        {
            return this.totalField;
        }
        set
        {
            this.totalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("remessa", IsNullable = false)]
    public List<retornoConsultaRemessa> remessas
    {
        get
        {
            return this.remessasField;
        }
        set
        {
            this.remessasField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class retornoConsultaRemessa
{

    private string motoristaCpfField;

    private string romaneioField;

    private string identificadorField;

    private string notaFiscalField;

    private string pedidoField;

    private System.DateTime dataEntregaField;

    private string ocorrenciaField;

    private string idOcorrenciaField;

    private string parentescoField;

    private string observacaoField;

    private string protocoloField;

    /// <remarks/>
    public string motoristaCpf
    {
        get
        {
            return this.motoristaCpfField;
        }
        set
        {
            this.motoristaCpfField = value;
        }
    }

    /// <remarks/>
    public string romaneio
    {
        get
        {
            return this.romaneioField;
        }
        set
        {
            this.romaneioField = value;
        }
    }

    /// <remarks/>
    public string identificador
    {
        get
        {
            return this.identificadorField;
        }
        set
        {
            this.identificadorField = value;
        }
    }

    /// <remarks/>
    public string notaFiscal
    {
        get
        {
            return this.notaFiscalField;
        }
        set
        {
            this.notaFiscalField = value;
        }
    }

    /// <remarks/>
    public string pedido
    {
        get
        {
            return this.pedidoField;
        }
        set
        {
            this.pedidoField = value;
        }
    }

    /// <remarks/>
    public System.DateTime dataEntrega
    {
        get
        {
            return this.dataEntregaField;
        }
        set
        {
            this.dataEntregaField = value;
        }
    }

    /// <remarks/>
    public string ocorrencia
    {
        get
        {
            return this.ocorrenciaField;
        }
        set
        {
            this.ocorrenciaField = value;
        }
    }

    /// <remarks/>
    public string idOcorrencia
    {
        get
        {
            return this.idOcorrenciaField;
        }
        set
        {
            this.idOcorrenciaField = value;
        }
    }

    /// <remarks/>
    public string parentesco
    {
        get
        {
            return this.parentescoField;
        }
        set
        {
            this.parentescoField = value;
        }
    }

    /// <remarks/>
    public string observacao
    {
        get
        {
            return this.observacaoField;
        }
        set
        {
            this.observacaoField = value;
        }
    }

    /// <remarks/>
    public string protocolo
    {
        get
        {
            return this.protocoloField;
        }
        set
        {
            this.protocoloField = value;
        }
    }
}
